---
title: "Data Acquisition"
format: html
editor: visual
---

Sample code to get athlete results data:

We might need to refresh the `x-api-key` field from time to time

```{r}
library(tidyverse)
library(httr2)

# base request 
base_req <- 
  request("https://graphql-prod-4829.edge.aws.worldathletics.org/graphql") |>
  req_method("POST") |>
  req_headers(
    Accept = "*/*",
    `Sec-Fetch-Site` = "same-site",
    `Accept-Language` = "en-CA,en-US;q=0.9,en;q=0.8",
    `Sec-Fetch-Mode` = "cors",
    `Accept-Encoding` = "gzip, deflate", # i removed the `br` here, that was causing errors
    Origin = "https://worldathletics.org",
    `User-Agent` = "Mozilla/5.0",
    Referer = "https://worldathletics.org/",
   # `Content-Length` = "895",
    Connection = "keep-alive",
    `Sec-Fetch-Dest` = "empty",
    `x-amz-user-agent` = "aws-amplify/3.0.2",
    Priority = "u=3, i",
    `x-api-key` = "da2-tfydjxrdwnaydebwsodqefmibe" # might need to update this sometimes
  )

```

I wonder if I can "quickly" rescrape the olympic results

```{r}
library(rvest)

# first, I need to get the competition ID's, which I did manually

competition_ids <- c(7153115, 7132391, 7093747, 6999193, 6977748, 6913163, 6951910, 6961749)

scrape_results <- function(competition_id, event_day) {
  Sys.sleep(0.5)
  base_req %>%
  req_body_json(
    list(
    operationName = "getCalendarCompetitionResults",
    variables = list(
      competitionId = competition_id,
      day = event_day,
      eventId = NULL
    ),
    query = "
      query getCalendarCompetitionResults($competitionId: Int, $day: Int, $eventId: Int) {
        getCalendarCompetitionResults(competitionId: $competitionId, day: $day, eventId: $eventId) {
          competition {
            dateRange
            endDate
            name
            rankingCategory
            startDate
            venue
          }
          eventTitles {
            eventTitle
            events {
              event
              eventId
              gender
              isRelay
              perResultWind
              withWind
              races {
                date
                day
                race
                raceId
                raceNumber
                results {
                  competitor {
                    teamMembers {
                      id
                      name
                      iaafId
                      urlSlug
                    }
                    id
                    name
                    iaafId
                    urlSlug
                    birthDate
                    hasProfile
                  }
                  mark
                  nationality
                  place
                  points
                  qualified
                  records
                  wind
                  remark
                  details {
                    event
                    eventId
                    raceNumber
                    mark
                    wind
                    placeInRound
                    placeInRace
                    points
                    overallPoints
                    placeInRoundByPoints
                    overallPlaceByPoints
                  }
                }
                startList {
                  competitor {
                    birthDate
                    country
                    id
                    name
                    urlSlug
                  }
                  order
                  pb
                  sb
                  bib
                }
              }
            }
          }
        }
      }
    "
  )
) %>% 
  req_perform() %>% 
  resp_body_json()
}

all_data <- tibble()

for(competition_id in competition_ids) {

event_days <-   
  base_req %>%
  req_body_json(
    list(
    operationName = "getCalendarCompetitionResults",
    variables = list(
      competitionId = competition_id,
      day = NULL,
      eventId = NULL
    ),
        query = "
      query getCalendarCompetitionResults($competitionId: Int, $day: Int, $eventId: Int) {
        getCalendarCompetitionResults(competitionId: $competitionId, day: $day, eventId: $eventId) {
          options {
            days {
              date
              day
            }
          }
        }
      }
      "
    )
    )%>% 
  req_perform() %>%
  resp_body_json() %>% 
  pluck("data", "getCalendarCompetitionResults", "options", "days") %>% 
  bind_rows() %>% 
  pull(day)

 results <- map(event_days, ~ scrape_results(competition_id, .x)) %>% 
   bind_rows() %>% 
  unnest_wider(data) %>% 
  #unnest_wider(getCalendarCompetitionResults) %>%
  unnest_wider(competition) %>% 
  unnest_longer(eventTitles) %>% 
  unnest_wider(eventTitles) %>% 
  unnest_longer(events) %>% 
  unnest_wider(events) %>% 
  unnest_longer(races) %>% 
  unnest_wider(races) %>% 
  unnest_longer(results) %>% 
  unnest_wider(results) %>% 
  rename(event_name = name) %>% 
  unnest_wider(competitor) %>% 
  unnest_longer(teamMembers, keep_empty = T) %>% 
  unnest_wider(teamMembers, names_sep = "_") 
 
 all_data <- bind_rows(all_data, bind_rows(results))

}

all_data <- all_data %>% janitor::clean_names()

write_csv(all_data, "olympics_data.csv")

```

```{r}

get_results_data <- function(athlete_id, year) {
  base_req |>
  req_body_json(
    list(
      operationName = "GetSingleCompetitorResultsDate",
      variables = list(
        resultsByYear = year,
        resultsByYearOrderBy = "date",
        id = athlete_id
      ),query = "
      query GetSingleCompetitorResultsDate($id: Int, $resultsByYearOrderBy: String, $resultsByYear: Int) {
        getSingleCompetitorResultsDate(
          id: $id,
          resultsByYear: $resultsByYear,
          resultsByYearOrderBy: $resultsByYearOrderBy
        ) {
          parameters {
            resultsByYear
          }
          resultsByDate {
            date
            competition
            competitionId
            eventId
            venue
            indoor
            disciplineCode
            disciplineNameUrlSlug
            typeNameUrlSlug
            discipline
            country
            category
            race
            place
            mark
            wind
            notLegal
            resultScore
            remark
            competitionId
            eventId
          }
          __typename
        }
      }
    "
  ), 
  type = "application/json"
  ) |>
  req_perform() |>
  resp_body_json()
}
```

so for each distinct athlete in `olympics_data.csv` dataset

```{r}
# all athletes who have made an olympic games between 1996 and 2021. 
# We could probably add the 2024 olympics to this if we want, which would be a good idea.

athlete_links <- read_csv("olympics_data.csv", show_col_types = F) %>% 
  distinct(url_slug) %>% 
  pull(url_slug)

#all_results <- tibble()
for (athlete_link in sample(athlete_links)) {
  # add a progress bar
  if(athlete_link %in% unique(all_results$athlete_link)) next
  
  if(n_distinct(all_results$athlete_link) %% 500 == 0 ) {
    cat(paste0("Processed ", n_distinct(all_results$athlete_link), " out of ", length(athlete_links), " athletes\n"))
  }

  athlete_id <- str_extract(athlete_link, "\\d+$")
  
  active_years <- 
  base_req %>% 
  req_body_json(list(
    operationName = "GetSingleCompetitorResultsDate",
    variables = list(id = athlete_id),
    query = "
      query GetSingleCompetitorResultsDate($id: Int) {
        getSingleCompetitorResultsDate(id: $id) {
          activeYears
        }
      }"
  )) %>% 
  req_perform() %>% 
  resp_body_json() %>% 
  pluck("data", "getSingleCompetitorResultsDate", "activeYears")
  
  if (is.null(active_years)) next
  
  Sys.sleep(0.5)
  
  active_years <- active_years %>% list_c() %>% parse_integer()
  
  results <- map(active_years, ~ get_results_data(athlete_id, .x))

  results_df <- 
    results %>% 
    bind_rows() %>% 
    unnest_wider(data) %>% 
    unnest_longer(resultsByDate) %>% 
    unnest_wider(resultsByDate) %>% 
    unnest_wider(parameters) %>% 
    janitor::clean_names() %>% 
    mutate(ahlete_id = athlete_id, 
           athlete_link = athlete_link)
  
  all_results <- bind_rows(all_results, results_df)
  
}

write_csv(all_results, "athlete_results_data.csv")

```
